mesh:
  type: rectangle
  nx: 64
  ny: 64
model:
  start_from_steady_state: False
  n_init: 2.0e+14
  S0n_fac: 0.03
  S0T_fac: 0.03
  T_init: 6.0e-4
  Ls_boost: 1.0
numerics:
  discretisation: CG
  do_streamline_upwinding: True
  phi_boundary_value: 0.03
physical:
  n_0: 2.0e+18
  nu: 0.03
  omega_ci: 9.6e+5
  R: 0.5
  T_e0: 6
time:
  num_steps: 50000
  info_freq: 25
  output_freq: 250
  t_end: 5000.0e-6
